subscription Events {
  events {
    __typename
    ... on Message {
      ...MessageFields
      user {
        ...UserFields
      }
      chat {
        id
      }
    }
    ... on MessageReactionsUpdated {
      message {
        ...MessageFields
        user {
          ...UserFields
        }
        chat {
          id
        }
      }
    }
  }
}
