services:
  server:
    build: ./server/
    restart: unless-stopped
    container_name: server
    depends_on:
      database:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SMTP_LOGIN: ${SMTP_LOGIN}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}

  database:
    image: postgres:18.4
    container_name: database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - "database_data:/var/lib/postgresql/"

  client:
    build: ./client/
    restart: unless-stopped
    container_name: client
    depends_on:
      - server

  gateway:
    image: caddy:2.11
    restart: unless-stopped
    container_name: gateway
    depends_on:
      - client
      - server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data/
      - caddy_config:/config/

volumes:
  database_data:
  caddy_data:
  caddy_config:
