query Chats($pagination: BasePaginationIn, $filters: ChatFiltersIn) {
  chats(pagination: $pagination, filters: $filters) {
    count
    chats {
      ...ChatFields
      participants {
        id
        isAdmin
        isMuted
        lastReadAt
        user {
          ...UserFields
        }
      }
    }
  }
}
