"""empty message

Revision ID: 18b9e9546f61
Revises: 3b422d589ce0
Create Date: 2026-08-03 04:29:05.156234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b9e9546f61'
down_revision: Union[str, Sequence[str], None] = '3b422d589ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancelled_refresh_tokens',
    sa.Column('jti', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti', name=op.f('uq_cancelled_refresh_tokens_jti'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cancelled_refresh_tokens')
    # ### end Alembic commands ###
