"""empty message

Revision ID: 36bc5640de66
Revises: c92a12e7afd4
Create Date: 2026-08-18 20:28:54.649802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36bc5640de66'
down_revision: Union[str, Sequence[str], None] = 'c92a12e7afd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_chat_profiles',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('last_message_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_public_chat_profiles_chat_id_chats'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_message_id'], ['users.id'], name=op.f('fk_public_chat_profiles_last_message_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public_chat_profiles')
    # ### end Alembic commands ###
