"""empty message

Revision ID: 474a6bc3f740
Revises: c92a12e7afd4
Create Date: 2026-08-16 17:39:39.557328

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "474a6bc3f740"
down_revision: Union[str, Sequence[str], None] = "c92a12e7afd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deferred_message_events",
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column(
            "type", sa.Enum("CREATE", name="deferredmessageeventtype"), nullable=False
        ),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.Column(
            "is_delivered",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_deferred_message_events_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.id"],
            name=op.f("fk_deferred_message_events_recipient_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deferred_message_events")
    # ### end Alembic commands ###
