"""empty message

Revision ID: 47f66e1b0697
Revises: 5e2c6aecabf1
Create Date: 2026-08-09 14:39:05.227428

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47f66e1b0697"
down_revision: Union[str, Sequence[str], None] = "5e2c6aecabf1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(), nullable=False))
    op.drop_constraint(op.f("uq_users_login"), "users", type_="unique")
    op.drop_constraint(op.f("uq_users_phone_number"), "users", type_="unique")
    op.create_unique_constraint(op.f("uq_users_email"), "users", ["email"])
    op.drop_column("users", "login")
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("phone_number", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users", sa.Column("login", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    op.create_unique_constraint(
        op.f("uq_users_phone_number"),
        "users",
        ["phone_number"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("uq_users_login"), "users", ["login"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("users", "email")
    # ### end Alembic commands ###
