"""empty message

Revision ID: c92a12e7afd4
Revises: f864588eabfc
Create Date: 2026-08-12 21:11:30.984356

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c92a12e7afd4"
down_revision: Union[str, Sequence[str], None] = "f864588eabfc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("fk_messages_user_id_users"),
        "messages",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_messages_user_id_users"), "messages", type_="foreignkey"
    )
    op.drop_column("messages", "user_id")
    # ### end Alembic commands ###
