"""u_users_online

Revision ID: 2fd13a0bad86
Revises: 3d8ac52f1b74
Create Date: 2026-09-16 20:22:13.927196

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2fd13a0bad86"
down_revision: Union[str, Sequence[str], None] = "3d8ac52f1b74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("last_online_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_online_at")
    # ### end Alembic commands ###
