"""u_chat_participants_last_read_at

Revision ID: 25edf4e9e665
Revises: 05232420fe4a
Create Date: 2026-08-27 04:38:47.060725

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25edf4e9e665"
down_revision: Union[str, Sequence[str], None] = "05232420fe4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_participants",
        sa.Column("last_read_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_participants", "last_read_at")
    # ### end Alembic commands ###
