"""u_sys_notifications_expires_at

Revision ID: 9b3f7c1a4e62
Revises: 0704ea73d326
Create Date: 2026-09-15 14:20:11.204518

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b3f7c1a4e62"
down_revision: Union[str, Sequence[str], None] = "0704ea73d326"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "system_notifications",
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("system_notifications", "expires_at")
    # ### end Alembic commands ###
