"""u_messages_type

Revision ID: 0704ea73d326
Revises: c5f6674663cc
Create Date: 2026-09-04 21:37:50.487133

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0704ea73d326"
down_revision: Union[str, Sequence[str], None] = "c5f6674663cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "type",
            postgresql.ENUM("TEXT", name="messagetype"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
