input BasePaginationIn {
  limit: Int
  offset: Int
}

type Chat implements IBaseType {
  id: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  type: EChatType!
  title: String!
  participants: [ChatParticipant!]!
  lastMessage: Message
}

input ChatFiltersIn {
  type: EChatType
}

union ChatInvalidInputErrorObjectNotFoundError = Chat | InvalidInputError | ObjectNotFoundError

union ChatInvalidInputErrorObjectNotFoundErrorObjectAlreadyExistsError = Chat | InvalidInputError | ObjectNotFoundError | ObjectAlreadyExistsError

type ChatParticipant implements IBaseType & IUser & IChat {
  id: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  user: User!
  chat: Chat!
  isAdmin: Boolean!
  isMuted: Boolean!
  lastReadAt: DateTime
}

input ChatParticipantIn {
  chatId: Int!
  userId: Int!
  isAdmin: Boolean!
  isMuted: Boolean!
}

union ChatParticipantObjectNotFoundError = ChatParticipant | ObjectNotFoundError

union ChatParticipantObjectNotFoundErrorObjectAlreadyExistsErrorInvalidInputError = ChatParticipant | ObjectNotFoundError | ObjectAlreadyExistsError | InvalidInputError

input ChatUpdateIn {
  title: String!
}

type ChatsMeta implements IBaseMeta {
  count: Int!
  chats: [Chat!]!
}

union ChatsMetaUnauthorizedError = ChatsMeta | UnauthorizedError

"""Date with time (isoformat)"""
scalar DateTime

enum EChatType {
  PRIVATE
  PUBLIC
}

enum EMessageType {
  TEXT
}

enum EUserRole {
  STUDENT
  TEACHER
}

interface IAppError {
  message: String!
}

interface IBaseMeta {
  count: Int!
}

interface IBaseType {
  id: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
}

interface IChat {
  chat: Chat!
}

interface IUser {
  user: User!
}

type InvalidInputError implements IAppError {
  message: String!
}

type JWTs {
  accessToken: String!
  refreshToken: String!
}

union JWTsObjectNotFoundError = JWTs | ObjectNotFoundError

union JWTsUnauthorizedErrorObjectNotFoundError = JWTs | UnauthorizedError | ObjectNotFoundError

type Message implements IBaseType & IUser & IChat {
  id: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  user: User!
  chat: Chat!
  text: String!
  type: EMessageType!
}

input MessageFiltersIn {
  chatId: Int!
  type: EMessageType
}

input MessageIn {
  chatId: Int!
  type: EMessageType!
  text: String!
}

union MessageObjectNotFoundError = Message | ObjectNotFoundError

type MessagesMeta implements IBaseMeta {
  count: Int!
  messages: [Message!]!
}

type Mutation {
  login(input: UserCredentialsIn!): JWTsObjectNotFoundError!
  refresh: JWTsUnauthorizedErrorObjectNotFoundError!
  logout: Void
  userCreate(input: UserIn!): UserObjectAlreadyExistsError!
  userUpdate(id: Int!, input: UserIn!): UserObjectAlreadyExistsErrorObjectNotFoundError!
  userDelete(id: Int!): Void
  userResetPasswordRequest(email: String!): ObjectNotFoundError
  userResetPasswordConfirm(id: Int!, code: String!): ObjectNotFoundError
  createPrivateChat(input: PrivateChatIn!): ChatInvalidInputErrorObjectNotFoundErrorObjectAlreadyExistsError!
  createPublicChat(input: PublicChatIn!): ChatInvalidInputErrorObjectNotFoundErrorObjectAlreadyExistsError!
  updateChat(chatId: Int!, input: ChatUpdateIn!): ChatInvalidInputErrorObjectNotFoundError!
  addParticipantToChat(input: ChatParticipantIn!): ChatParticipantObjectNotFoundErrorObjectAlreadyExistsErrorInvalidInputError!
  removeParticipantFromChat(chatId: Int!, userId: Int!): Void
  leaveChat(chatId: Int!): ChatInvalidInputErrorObjectNotFoundError!
  updateChatParticipantPermissions(input: ChatParticipantIn!): ChatParticipantObjectNotFoundError!
  markChatRead(chatId: Int!): ChatParticipantObjectNotFoundError!
  createMessage(input: MessageIn!): MessageObjectNotFoundError!
  createSystemNotification(input: SystemNotificationIn!): SystemNotification!
  updateSystemNotification(id: Int!, input: SystemNotificationIn!): SystemNotificationObjectNotFoundError!
  markSystemNotificationRead(id: Int!): ObjectNotFoundError
}

type ObjectAlreadyExistsError implements IAppError {
  message: String!
}

type ObjectNotFoundError implements IAppError {
  message: String!
}

input PrivateChatIn {
  participantId: Int!
}

input PublicChatIn {
  title: String!
  participantIds: [Int!]
}

type Query {
  me: UserObjectNotFoundError!
  users(pagination: BasePaginationIn = null, filters: UserFiltersIn = null): UsersMeta!
  meChats(pagination: BasePaginationIn = null, filters: ChatFiltersIn = null): ChatsMetaUnauthorizedError!
  chats(pagination: BasePaginationIn = null, filters: ChatFiltersIn = null): ChatsMeta!
  messages(filters: MessageFiltersIn!, pagination: BasePaginationIn = null): MessagesMeta!
  meSystemNotifications(pagination: BasePaginationIn = null, filters: SystemNotificationFiltersIn = null): SystemNotificationsMeta!
  systemNotifications(pagination: BasePaginationIn = null): SystemNotificationsMeta!
  health: Int!
}

type Subscription {
  events: Message!
}

type SystemNotification implements IBaseType {
  id: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  title: String!
  text: String!
}

input SystemNotificationFiltersIn {
  onlyUnread: Boolean
}

input SystemNotificationIn {
  title: String!
  text: String!
}

union SystemNotificationObjectNotFoundError = SystemNotification | ObjectNotFoundError

type SystemNotificationsMeta implements IBaseMeta {
  count: Int!
  systemNotifications: [SystemNotification!]!
}

type UnauthorizedError implements IAppError {
  message: String!
}

type User implements IBaseType {
  id: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  name: String!
  surname: String!
  patronymic: String
  email: String!
  role: EUserRole!
  isAdmin: Boolean!
  fullName: String!
}

input UserCredentialsIn {
  email: String!
  password: String!
}

input UserFiltersIn {
  searchQuery: String
  role: EUserRole
  isAdmin: Boolean
}

input UserIn {
  name: String!
  surname: String!
  patronymic: String
  email: String!
  role: EUserRole!
  isAdmin: Boolean!
}

union UserObjectAlreadyExistsError = User | ObjectAlreadyExistsError

union UserObjectAlreadyExistsErrorObjectNotFoundError = User | ObjectAlreadyExistsError | ObjectNotFoundError

union UserObjectNotFoundError = User | ObjectNotFoundError

type UsersMeta implements IBaseMeta {
  count: Int!
  users: [User!]!
}

"""Represents NULL values"""
scalar Void
