import os

POSTGRES_DB = os.getenv("POSTGRES_DB", "")
POSTGRES_USER = os.getenv("POSTGRES_USER", "")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "")
DATABASE_URL = f"postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@database:5432/{POSTGRES_DB}"

LIMIT = 10
OFFSET = 0

MIN_PASSWORD_LEN = 8

UVICORN_HOST = "0.0.0.0"
UVICORN_PORT = 8000

JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY", "")
JWT_ENCRYPTION_ALGORITHM = "HS256"
JWT_ACCESS_EXP_MINUTES = 5
JWT_REFRESH_EXP_DAYS = 14

SMTP_LOGIN = os.getenv("SMTP_LOGIN", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
SMTP_SERVER = "smtp.yandex.ru"
SMTP_PORT = 587
