name: ci

on:
  push:
  workflow_dispatch:

jobs:
  lint-py:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Setup dependencies and launch linters
        working-directory: ./server/
        run: |
          uv sync
          uv run ruff format --check .
          uv run ruff check .
          uv run ty check .
  lint-ts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Setup dependencies and launch linters
        working-directory: ./client/
        run: |
          npm install
          npm run lint
          npm run format:check
          npm run type-check
  test-server-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Setup dependencies and launch schemagen
        working-directory: ./server/
        run: |
          uv sync
          uv run schemagen
      - name: Check diff
        run: git diff --exit-code
  test-client-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Setup dependencies and launch schemagen
        working-directory: ./client/
        run: |
          npm install
          npm run codegen
      - name: Check diff
        run: git diff --exit-code
  validate-caddyfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Validate Caddyfile
        run: docker run --rm -v ${{ github.workspace }}/Caddyfile:/etc/caddy/Caddyfile:ro caddy:2.11 caddy validate --config /etc/caddy/Caddyfile
